package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/devton/couchgraph/internal/couch"
	"github.com/devton/couchgraph/internal/graph/generated"
	"github.com/devton/couchgraph/internal/graph/model"
)

// Movies is the resolver for the movies field on Director (1:N relationship).
func (r *directorResolver) Movies(ctx context.Context, obj *model.Director) ([]*model.Movie, error) {
	falseVal := false
	res, err := r.Repo.QueryView(ctx, couch.ViewOptions{
		DesignDoc: "movies",
		ViewName:  "by_director_id",
		Key:       obj.ID,
		Reduce:    &falseVal,
	})
	if err != nil {
		return nil, err
	}

	movies := make([]*model.Movie, 0, len(res.Rows))
	for _, row := range res.Rows {
		if m, ok := row.Value.(map[string]any); ok {
			movies = append(movies, mapToMovie(m))
		}
	}
	return movies, nil
}

// Director is the resolver for the director field on Movie (1:1 relationship via DataLoader).
func (r *movieResolver) Director(ctx context.Context, obj *model.Movie) (*model.Director, error) {
	if obj.DirectorID == nil || *obj.DirectorID == "" {
		return nil, nil
	}

	loader := couch.NewLoader(r.Repo)
	doc, err := loader.LoadAndWait(ctx, *obj.DirectorID)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, nil
	}

	return mapToDirector(doc), nil
}

// Movie is the resolver for the movie field on Query.
func (r *queryResolver) Movie(ctx context.Context, id string) (*model.Movie, error) {
	loader := couch.NewLoader(r.Repo)
	doc, err := loader.LoadAndWait(ctx, id)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, nil
	}

	return mapToMovie(doc), nil
}

// Movies is the resolver for the movies collection field on Query.
func (r *queryResolver) Movies(ctx context.Context, genre *string, minRating *float64, limit *int) ([]*model.Movie, error) {
	selector := map[string]any{"type": "movie"}
	if genre != nil && *genre != "" {
		selector["genres"] = map[string]any{"$in": []string{*genre}}
	}
	if minRating != nil {
		selector["rating"] = map[string]any{"$gte": *minRating}
	}

	findOpts := couch.FindOptions{
		Selector: selector,
	}
	if limit != nil && *limit > 0 {
		findOpts.Limit = *limit
	}

	res, err := r.Repo.Find(ctx, findOpts)
	if err != nil {
		return nil, err
	}

	movies := make([]*model.Movie, 0, len(res.Docs))
	for _, doc := range res.Docs {
		movies = append(movies, mapToMovie(doc))
	}
	return movies, nil
}

// Director is the resolver for the director field on Query.
func (r *queryResolver) Director(ctx context.Context, id string) (*model.Director, error) {
	loader := couch.NewLoader(r.Repo)
	doc, err := loader.LoadAndWait(ctx, id)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, nil
	}

	return mapToDirector(doc), nil
}

// Directors is the resolver for the directors collection field on Query.
func (r *queryResolver) Directors(ctx context.Context) ([]*model.Director, error) {
	falseVal := false
	res, err := r.Repo.QueryView(ctx, couch.ViewOptions{
		DesignDoc: "movies",
		ViewName:  "all_directors",
		Reduce:    &falseVal,
	})
	if err != nil {
		return nil, err
	}

	directors := make([]*model.Director, 0, len(res.Rows))
	for _, row := range res.Rows {
		if d, ok := row.Value.(map[string]any); ok {
			directors = append(directors, mapToDirector(d))
		}
	}
	return directors, nil
}

// Director returns generated.DirectorResolver implementation.
func (r *Resolver) Director() generated.DirectorResolver { return &directorResolver{r} }

// Movie returns generated.MovieResolver implementation.
func (r *Resolver) Movie() generated.MovieResolver { return &movieResolver{r} }

type (
	directorResolver struct{ *Resolver }
	movieResolver    struct{ *Resolver }
)
