package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"

	"github.com/ton/couchgraph/internal/couch"
	"github.com/ton/couchgraph/internal/graph/generated"
	"github.com/ton/couchgraph/internal/graph/model"
)

// UpsertDoc is the resolver for the upsertDoc field.
func (r *mutationResolver) UpsertDoc(ctx context.Context, input model.UpsertInput) (*model.MutationResult, error) {
	data, ok := input.Data.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("upsertDoc: 'data' must be a JSON object")
	}

	var id, rev string
	if input.ID != nil {
		id = *input.ID
	}
	if input.Rev != nil {
		rev = *input.Rev
	}

	newID, newRev, err := r.Repo.Upsert(ctx, id, rev, data)
	if err != nil {
		return nil, err
	}

	return &model.MutationResult{Ok: true, ID: newID, Rev: newRev}, nil
}

// DeleteDoc is the resolver for the deleteDoc field.
func (r *mutationResolver) DeleteDoc(ctx context.Context, input model.DeleteInput) (*model.MutationResult, error) {
	newRev, err := r.Repo.Delete(ctx, input.ID, input.Rev)
	if err != nil {
		return nil, err
	}
	return &model.MutationResult{Ok: true, ID: input.ID, Rev: newRev}, nil
}

// BulkDocs is the resolver for the bulkDocs field.
func (r *mutationResolver) BulkDocs(ctx context.Context, input model.BulkDocsInput) (*model.BulkResult, error) {
	docs := make([]map[string]any, 0, len(input.Docs))
	for _, d := range input.Docs {
		data, ok := d.Data.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("bulkDocs: each 'data' must be a JSON object")
		}
		doc := make(map[string]any, len(data)+2)
		for k, v := range data {
			doc[k] = v
		}
		if d.ID != nil {
			doc["_id"] = *d.ID
		}
		if d.Rev != nil {
			doc["_rev"] = *d.Rev
		}
		docs = append(docs, doc)
	}

	results, err := r.Repo.BulkDocs(ctx, docs)
	if err != nil {
		return nil, err
	}

	gqlResults := make([]*model.MutationResult, 0, len(results))
	for _, res := range results {
		ok, _ := res["ok"].(bool)
		id, _ := res["_id"].(string)
		rev, _ := res["_rev"].(string)
		gqlResults = append(gqlResults, &model.MutationResult{
			Ok:  ok,
			ID:  id,
			Rev: rev,
		})
	}

	return &model.BulkResult{Results: gqlResults}, nil
}

// Document is the resolver for the document field.
func (r *queryResolver) Document(ctx context.Context, id string) (*model.Document, error) {
	loader := couch.NewLoader(r.Repo)
	doc, err := loader.LoadAndWait(ctx, id)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, nil
	}
	return rawToDocument(doc), nil
}

// Documents is the resolver for the documents field.
// Uses DataLoader to batch all IDs into a single _bulk_get request.
func (r *queryResolver) Documents(ctx context.Context, ids []string) ([]*model.Document, error) {
	loader := couch.NewLoader(r.Repo)

	// Register all IDs with the loader (they'll be batched).
	channels := make([]<-chan couch.LoadResult, len(ids))
	for i, id := range ids {
		channels[i] = loader.Load(id)
	}

	// Dispatch fires the single _bulk_get.
	loader.Dispatch(ctx)

	// Collect results preserving input order.
	docs := make([]*model.Document, len(ids))
	for i, ch := range channels {
		res := <-ch
		if res.Err != nil {
			return nil, res.Err
		}
		if res.Doc != nil {
			docs[i] = rawToDocument(res.Doc)
		}
	}
	return docs, nil
}

// FindDocs is the resolver for the findDocs field.
func (r *queryResolver) FindDocs(ctx context.Context, input model.FindInput) (*model.FindResult, error) {
	selector, ok := input.Selector.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("findDocs: 'selector' must be a JSON object")
	}

	opts := couch.FindOptions{Selector: selector}

	if len(input.Fields) > 0 {
		opts.Fields = input.Fields
	}
	if len(input.Sort) > 0 {
		sort := make([]map[string]any, 0, len(input.Sort))
		for _, s := range input.Sort {
			if m, ok := s.(map[string]any); ok {
				sort = append(sort, m)
			}
		}
		opts.Sort = sort
	}
	if input.Limit != nil {
		opts.Limit = *input.Limit
	}
	if input.Skip != nil {
		opts.Skip = *input.Skip
	}
	if input.Bookmark != nil {
		opts.Bookmark = *input.Bookmark
	}

	res, err := r.Repo.Find(ctx, opts)
	if err != nil {
		return nil, err
	}

	gqlDocs := make([]*model.Document, 0, len(res.Docs))
	for _, raw := range res.Docs {
		gqlDocs = append(gqlDocs, rawToDocument(raw))
	}

	result := &model.FindResult{Docs: gqlDocs}
	if res.Bookmark != "" {
		result.Bookmark = &res.Bookmark
	}
	if res.Warning != "" {
		result.Warning = &res.Warning
	}
	return result, nil
}

// QueryView is the resolver for the queryView field.
func (r *queryResolver) QueryView(ctx context.Context, input model.ViewInput) (*model.ViewResult, error) {
	opts := couch.ViewOptions{
		DesignDoc: input.DesignDoc,
		ViewName:  input.ViewName,
		Key:       input.Key,
		Keys:      input.Keys,
		StartKey:  input.StartKey,
		EndKey:    input.EndKey,
	}
	if input.Limit != nil {
		opts.Limit = *input.Limit
	}
	if input.Skip != nil {
		opts.Skip = *input.Skip
	}
	if input.Descending != nil {
		opts.Descending = *input.Descending
	}
	if input.IncludeDocs != nil {
		opts.IncludeDocs = *input.IncludeDocs
	}
	if input.Reduce != nil {
		opts.Reduce = input.Reduce
	}
	if input.Group != nil {
		opts.Group = input.Group
	}
	if input.GroupLevel != nil {
		opts.GroupLevel = input.GroupLevel
	}

	res, err := r.Repo.QueryView(ctx, opts)
	if err != nil {
		return nil, err
	}

	rows := make([]*model.ViewRow, 0, len(res.Rows))
	for _, vr := range res.Rows {
		row := &model.ViewRow{
			Key:   vr.Key,
			Value: vr.Value,
		}
		if vr.ID != "" {
			row.ID = &vr.ID
		}
		if vr.Doc != nil {
			row.Doc = rawToDocument(vr.Doc)
		}
		rows = append(rows, row)
	}

	return &model.ViewResult{
		Rows:      rows,
		TotalRows: res.TotalRows,
		Offset:    res.Offset,
	}, nil
}

// Databases is the resolver for the databases field.
func (r *queryResolver) Databases(ctx context.Context) ([]string, error) {
	return r.Repo.Databases(ctx)
}

// ServerInfo is the resolver for the serverInfo field.
func (r *queryResolver) ServerInfo(ctx context.Context) (any, error) {
	return r.Repo.ServerInfo(ctx)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
