// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Input for a bulk write (create/update/delete) operation.
type BulkDocsInput struct {
	Docs []*UpsertInput `json:"docs"`
}

type BulkResult struct {
	Results []*MutationResult `json:"results"`
}

// Input for deleting a document.
type DeleteInput struct {
	ID  string `json:"_id"`
	Rev string `json:"_rev"`
}

// A raw JSON document stored in CouchDB.
// Fields _id and _rev are always present on fetched documents.
type Document struct {
	ID  string `json:"_id"`
	Rev string `json:"_rev"`
	// The remaining fields of the document as a raw JSON map.
	// Use typed queries (via future schema extensions) for strongly-typed access.
	Data any `json:"data"`
}

// Input for a Mango selector query (_find).
type FindInput struct {
	// JSON-encoded Mango selector, e.g. {"type": "user"}
	Selector any `json:"selector"`
	// Fields to return (projection). Empty means return all fields.
	Fields []string `json:"fields,omitempty"`
	// Sort descriptors, e.g. [{"name": "asc"}]
	Sort  []any `json:"sort,omitempty"`
	Limit *int  `json:"limit,omitempty"`
	Skip  *int  `json:"skip,omitempty"`
	// Opaque bookmark from a previous FindResult for cursor pagination.
	Bookmark *string `json:"bookmark,omitempty"`
}

// Result of a Mango _find query.
type FindResult struct {
	Docs []*Document `json:"docs"`
	// Opaque bookmark for cursor-based pagination (pass to next findDocs call).
	Bookmark *string `json:"bookmark,omitempty"`
	// Warning message from CouchDB if the query used a slow index.
	Warning *string `json:"warning,omitempty"`
}

type Mutation struct {
}

type MutationResult struct {
	Ok  bool   `json:"ok"`
	ID  string `json:"_id"`
	Rev string `json:"_rev"`
}

type Query struct {
}

// Input for creating or replacing a document.
type UpsertInput struct {
	// Optional document ID. If omitted, a new UUIDv7 ID is generated.
	// If the document already exists, _rev must be provided to update it.
	ID *string `json:"_id,omitempty"`
	// Required when updating an existing document.
	Rev *string `json:"_rev,omitempty"`
	// Document body (will be merged with _id/_rev).
	Data any `json:"data"`
}

// Input for a CouchDB View query.
type ViewInput struct {
	DesignDoc string `json:"designDoc"`
	ViewName  string `json:"viewName"`
	// Exact single key match (e.g. key: "Action" or key: 2010).
	Key any `json:"key,omitempty"`
	// Multiple exact keys match (e.g. keys: ["Action", "Sci-Fi"]).
	Keys []any `json:"keys,omitempty"`
	// Start of key range (inclusive, or exclusive if descending).
	StartKey any `json:"startKey,omitempty"`
	// End of key range (inclusive).
	EndKey      any   `json:"endKey,omitempty"`
	Limit       *int  `json:"limit,omitempty"`
	Skip        *int  `json:"skip,omitempty"`
	Descending  *bool `json:"descending,omitempty"`
	IncludeDocs *bool `json:"includeDocs,omitempty"`
	Reduce      *bool `json:"reduce,omitempty"`
	// Group by key when reduce is enabled.
	Group *bool `json:"group,omitempty"`
	// Group level for array keys in reduce views.
	GroupLevel *int `json:"groupLevel,omitempty"`
}

type ViewResult struct {
	Rows      []*ViewRow `json:"rows"`
	TotalRows int        `json:"totalRows"`
	Offset    int        `json:"offset"`
}

// Result of a CouchDB View (_design/_view) query.
type ViewRow struct {
	ID    *string   `json:"id,omitempty"`
	Key   any       `json:"key,omitempty"`
	Value any       `json:"value,omitempty"`
	Doc   *Document `json:"doc,omitempty"`
}
